### ISSUE TITLE
Bromite patches?

### ISSUE THREAD

**Issue by r3muxd** [kiwibrowser/src#10]
Would it make sense to add some features from @csagan5 's Bromite?
Like anti-fingerprinting and #enable-horizontal-tab-swircher and optional degoogling. 
I don't know how the licensing would work though.

**Comment by hjyoung1** [comment]
#enable-horizontal-tab-swircher
Is already available in chrome://flags
![Screenshot_20200418-225504~2](https://user-images.githubusercontent.com/45882061/79644642-d9c0fd00-81c7-11ea-94be-27f16f70379a.jpg)

**Comment by DJCrashdummy** [comment]
perhaps even merging may be worth considering?

**Comment by Dev-i-l** [comment]
hey @r3muxd , on a discussion in discord arnaud said he won't add patches from bromite, because he thinks that fingerprinting takes place at much deeper levels and the patches from bromite make you stand out in a crowd, remarking you have something to hide which will gain more attraction and the approach of kiwi is simple: to block requests, so you can close this issue buddy.
PS: IF YOU WANT TO SEE IT FOR YOURSELF I CAN SEND A SCREENSHOT

**Comment by d3ward** [comment]
#41
