### ISSUE TITLE
APKs on github do not allow app installation without uninstall first 

### ISSUE THREAD

**Issue by rancidfrog** [kiwibrowser/src#103]
There are numerous apps which use github as primary release source, with automatic notifications on new releases; i.e. Newpipe, fairemail, ...

Whereas kiwi requires uninstall first, which means settings will need to be redone.

![](https://i.imgur.com/zPPMmdR.png)

![](https://i.imgur.com/rR1uw0e.png)

Why is key random, which forces new installs each time?

**Comment by kiwibrowser** [comment]
A fix is planned tomorrow.

The flow will be like this:
 - Build APK using a random key (so anyone that just forks the project can build, and nobody can sign unauthorized builds of Kiwi)
 - Builds are then signed by Kiwi key server (only signed, unmodified)
 - Builds then go through Play Store to get signed and scanned/certified by Google and back to GitHub

**Comment by kiwibrowser** [comment]
Still working on it

**Comment by kiwibrowser** [comment]
Task in progress still

**Comment by tiwarimanu** [comment]
Kiwi is dead

**Comment by archon810** [comment]
Looks like this can be closed as signed github release builds are now available.

**Comment by kiwibrowser** [comment]
Yes, and it's working quite well. The Play Store signed builds are functional too. I'm waiting a bit before pushing it everywhere because I'm doing additional fixes right now.

**Comment by archon810** [comment]
@kiwibrowser We're preparing a story about the revival of the builds on Android Police. Any Play Store ETAs would be great!

**Comment by kiwibrowser** [comment]
@archon810 The new build is currently being tested on a subset of users.
If the stability is good enough, then it will expand to more and more users in the coming days.
Normally it was a secret as this was a test build :)
For now there is still some important crashes I want to fix (sometimes you need to clear cache / reinstall the app if you have issues).

When Mozilla launched the new Firefox, a lot of users suddenly shifted to Kiwi.
According to the Play Store, now Kiwi has 800'000 active daily users (not just downloads, but active users).

Maintaining such large projects and compatibility is time consuming and requires lot of attention.

When I started Kiwi, I didn't expect it would get that popular, I just wanted to add functionalities that made sense for me and fix a couple of performance issues in Chromium.

Brendan Eich, the CEO of Brave Software and former CEO of Mozilla mentioned it in several tweets.
https://twitter.com/BrendanEich/status/1276939902840528896
https://twitter.com/BrendanEich/status/1303387641287553025

Such alliance is a very interesting idea, I think it may still be possible to convince step by step Google to integrate more and more code changes coming from Kiwi back into Chromium.

**Comment by bitsper2nd** [comment]
Thanks for your hard work. Foss development must be really tiring, but I see that you still enjoy maintaining your craft. Sadly users want to see a number change in the browser and take all the development for granted. If its not the latest version, its obsolete for them. And more pressure for you the dev comes to stay up to date. You are kinda doing the same as Mozilla with their Firefox ESR, using a stable base and backporting security updates. But still many users don't understand this concept of long term support since they have the expectations of receiving daily software updates. Maybe for future versions when you rebase, having a moniker that this is supposed to be an LTS or ESR like browser might be helpful for clarification.
