### ISSUE TITLE
Create .patch files for easy reusing of Kiwi's code

### ISSUE THREAD

**Issue by Eddi2015** [kiwibrowser/src#13]
Hello Arnaud,

first of all a huge thank you for fully open-sourcing Kiwi. As you said in your XDA post, it would be great if other projects would use your code for extension support, performance improvements etc. Unfortunately this repo is basically a modified source tree of an old chromium version. Would it be possible for you to create the relevant .patch files using some sort of diff tool, so that it's easier to apply your code on a newer/other chromium base? I've already tried creating a diff against the upstream base 77.0.3865.116 (https://github.com/chromium/chromium/archive/77.0.3865.116.tar.gz). Unfortunately the diff is serveral gigabytes big and I don't have a clear overview which files are relevant and were changed. As I said earlier, this would improve the situation drastically for other browsers, such as Bromite and others (https://github.com/bromite/bromite/issues/527). It would be nice if you take a look at it. 

Greetings,
Eddi2015

**Comment by kiwibrowser** [comment]
Hello Eddi2015,

Essentially, when you browse the repository, you can ignore what is written Sync with Chromium since it's the code that I'm 100% sure is base / vanilla Chromium / boring.

It's a heavily modified Chromium yes.

For example, with extensions it's possible to sort outside a patch, if you are interested I can do that for you (and that should unlock significant progress specific to extensions).

But keep in mind that it's huge work if you actually want to maintain such thing, this is why Kiwi is forked away from Chromium-base (it may come back in few weeks, or not, depending on many factors, including collaboration with other browsers).

If you need help building the browser to explore how the functionalities are coded, feel free to ask (normally the documentation and building instructions are functional)

**Comment by Eddi2015** [comment]
> For example, with extensions it's possible to sort outside a patch, if you are interested I can do that for you (and that should unlock significant progress specific to extensions).

Well I'm indeed intersted, but I don't have any experience regarding chromium's codebase, so you wouldn't create the patch specifically for me, but rather for people with more knowledge. For example the maintainer of Bromite @csagan5 would accept a PR which adds extension support, but I'm not sure if he is ready to mainatin that huge patch set and if you, Arnaud, would be willing to send a PR to him. As I said before I'm quite a beginner when it comes to coding (I understand the basics of Java and I do some HTML, CSS from time to time), so you can't count on me. On the other hand, it might help you as well. If you have the intention of updating Kiwi to the latest chromium upstream release, then such a patch would be handy for you as well. And about the performance improvements of Kiwi ("partial rasterisation of tiles"): Couldn't you upstream those, so that everyone can benefit from those improvements? 

About Kiwi itself: Currently I see the problem that Kiwi's codebase is quite outdated compared to upstream. It does not only lack important security fixes, but probably also (some) newer features (not just user-facing, also HTML/JS/CSS features) and in the future it'll only get worse and Kiwi will fall behind more and more. Additionally backporting isn't an ideal solution in the longterm, I think, because the codebase will differ more and more with each release and it'll be harder to know which vulnerabilities affect Kiwi and how to correctly fix them. The only solution I can see is to upstream as much code as possible and keep the rest with .patch files. 

What is your opinion on these topics?

Regards, 
Eddi2015

**Comment by kiwibrowser** [comment]
For now we can backport a couple of fixes, or even the whole Java UI, that would be fine but in the long-term.

I've actually discussed with @csagan5 yesterday about this.
Bromite has the same problem as we have too. It's very costly to maintain such heavy fork.

I'm negotiating and supporting 2 large organisations to create some sort of symbiosis where they import a lot of the Kiwi functionalities (including extensions), and this is exactly the reason why I want other browsers to adopt our changes.

I think this may succeed, and we would essentially rebase on top of a "competitor" and follow their core changes.

The other alternative is that we follow Chromium's updates, but we need more eyes and hands on the project to ensure sustainability.

One solution is to hire full-time developers, which fundraising can solve but I'd rather not go that way (though YCombinator invited me in California about Kiwi specifically) because I want to keep Kiwi as a passion, with relatively limited pressure.

Growing the user base significantly would allow that too (as we could have enough influence to partner with Google).

So let's see, time will say, the goal is eventually to rebase. Who, where, how, when is still partially a question mark.

**Comment by kiwibrowser** [comment]
We could also relatively "easily" backport the whole UI.
It's long, but not difficult.

**Comment by kiwibrowser** [comment]
https://github.com/kiwibrowser/patches/blob/master/0001-Kiwi-Introduce-extensions-support-R80.patch

patch for 80.0.3987.58 which is a relatively recent version

**Comment by kiwibrowser** [comment]
I'll close this for now (as there is on-going discussion with ungoogled-chromium where I'll see if I can help them to go onboard)

**Comment by dvalter** [comment]
> https://github.com/kiwibrowser/patches/blob/master/0001-Kiwi-Introduce-extensions-support-R80.patch
> 
> patch for 80.0.3987.58 which is a relatively recent version

But it's of an unacceptable quality. I mean it does not correspond to code in this very repository and clearly was never attempted to be built.

**Comment by kiwibrowser** [comment]
@dvalter The patch is based off a quite recent unmodified version of Chromium and is really the changes needed to do.

Did you try to compile Kiwi ? you can try to navigate around and see how everything behaves (and I can assure you that 100% of the code is there)

**Comment by dvalter** [comment]
> The patch is based off a quite recent unmodified version of Chromium and is really the changes needed to do.

It _does not_. I tried to build Chromium of the said version with your patch, and there's no way it will work simply because you clearly break C++ code. Let alone gn flags that are hard to figure out something that will build __and__ work.

> Did you try to compile Kiwi ? you can try to navigate around and see how everything behaves (and I can assure you that 100% of the code is there)

It totally may be, but it's not 80.0.3987.58 or anything close to it. A believe it's not even a 77.x as your chrome/VERSION says. It looks to me more like 69.x frankenstein.

**Comment by kiwibrowser** [comment]
Absolutely about the frankenstein, it's a choice, it's the main reason why I forked Chromium to make different choices and create different software. Like Opera living its own life, independent from Chromium.

For example, ManifestV2 vs ManifestV3 (Google limiting adblockers), we collectively decided to keep it, no matter if it costs development time.

At the end, Kiwi is getting quite far from vanilla Chromium and keep in mind that when you ask for an extension patch over vanilla Chromium it doesn't directly make sense from a technical perspective since the core is heavily modified as well.
So to build this patch, I had to squash and cherry-pick all the changes that I thought are relevant and useful to see (and you can get something useful out of it).

See it as a guide.

The .gn args flags, are literally 1:1 the one you can find in the README.
Of course there is work to do, this patch is like a map/guidance for developers on what is expected to do.
Chromium changes everyday so the patch itself is not so important by itself, and if you start your own Chromium browser you have to take ownership.

It's efforts, I agree, but much much less than if you start from zero.

Here are the steps to follow:

1) enable_extensions / enable_plugins
2) enforce building with extensions and guest views in .gn files (overriding the asserts)
3) adding missing references in .gn files by enabling desktop specific references
(the if (is_android) { } else desktop { } to change to have both conditions to be active)
4) adding missing ressources in grdp files (this is super easy, even the easiest)
5) now you have extensions running, and can access in chrome://extensions
but you cannot load it from anywhere so you need to intercept installations of extensions (.crx) from Chrome Web Store or the store you
6) extensions are now installable and run in the background, so you need to add actions button in your UI the Kiwi repo provides a functional example of that here: 
https://github.com/kiwibrowser/src/blob/b1ea3ea95d8ac15fc0b49acd83ba2f8b1aaa8d2b/chrome/android/java/src/org/chromium/chrome/browser/appmenu/AppMenu.java#L304
7) the concept of windows, and tabs, is completely different on Android from desktop 
so you need to fix all exported APIs to behave coherently and implement platform specific placeholders

essentially the patch covers 1,2,3,4,5. 6 and 7 you decide how it's connected to the UI (again 100% is in the Kiwi repo)

You have the steps, you have a functional and ready to build reference repo, a patch that outlines most of the changes.
It's a long road, and your choice whether you want to walk through it or not.

**Comment by dvalter** [comment]
> Absolutely about the frankenstein, it's a choice, it's the main reason why I forked Chromium to make different choices and create different software. Like Opera living its own life, independent from Chromium.

> For example, ManifestV2 vs ManifestV3 (Google limiting adblockers), we collectively decided to keep it, no matter if it costs development time.

Good luck on that, hope you'll manage to keep Kiwi safe and up-to-date while doing so.

> So to build this patch, I had to squash and cherry-pick all the changes that I thought are relevant and useful to see (and you can get something useful out of it).

I thought it would include something more complete than an untested merge/squash of your changes. Probably it should be stated somewhere in the README.

[Here](https://github.com/dvalter/chromium_extension_patches) I made some tweaks to your R80 patch including some missing mock/placeholder files from Kiwi source so it now builds, starts and runs extensions. Some changes regarding linking errors are pretty rough and likely to break something.

Thank you for your response and instruction.

Also could you please educate me about the reason behind enabling plugins? At the first glance disabling plugins does not prevent extensions from working and reduce amount of the required code changes.

**Comment by kiwibrowser** [comment]
@dvalter I admire the effort, it's great what you did. I see that you were determined.

At first I thought you wanted a ready-made solution and complaining without understanding that some of my time is genuinely limited, but I can say that I was absolutely wrong, so I want to apologize on that.

The reason behind enabling plugins is that the developers of Chromium are assuming that enable_extensions and enable_plugins are always enabled but actually there are a couple of cross-references and inter-dependencies.

In theory, the patch also allows to run Flash plugin.

Regarding the UI, it's actually small and easy compared to the rest of the code AppMenu.java https://github.com/kiwibrowser/src/blob/503b2a9351fd52ca96b063d78fb3600e42e8fe74/chrome/android/java/src/org/chromium/chrome/browser/appmenu/AppMenu.java#L273

and it's JNI bound layer:

https://github.com/kiwibrowser/src/blob/b1ea3ea95d8ac15fc0b49acd83ba2f8b1aaa8d2b/chrome/browser/android/appmenu/app_menu.cc#L273

For compatibility, the critical part is "tabs_api.cc", "tabs_api.h" and such folder in general:
https://github.com/kiwibrowser/src/tree/b1ea3ea95d8ac15fc0b49acd83ba2f8b1aaa8d2b/chrome/browser/extensions/api/tabs

The best is to extract diff between 503b2a9351fd52ca96b063d78fb3600e42e8fe74 and 736b3d7ff7b11ecdb8740699083f855872f21861 on this specific folder.

Again, congratulations for reaching such step, I appreciate it, and I have shared the results with fellow developers.

**Comment by csagan5** [comment]
> the developers of Chromium are assuming that enable_extensions and enable_plugins are always enabled but actually there are a couple of cross-references and inter-dependencies.

This has happened and still happens often for various build flags; combination of flags are never tested upstream except for the one used for the official Chromium build.

**Comment by csagan5** [comment]
> But it's of an unacceptable quality. I mean it does not correspond to code in this very repository and clearly was never attempted to be built.

@dvalter this is an old problem, see https://github.com/kiwibrowser/android/issues/12#issuecomment-435690397

I think the best for the community would be if someone starts maintaining the patches (those in [this repo](https://github.com/kiwibrowser/src) and in the [patches repo](https://github.com/kiwibrowser/patches), since the [android one](https://github.com/kiwibrowser/android) has never had anything in it).

The best would be to merge them into [ungoogled-chromium-android](https://github.com/wchen342/ungoogled-chromium-android) by @wchen342 and/or [Vanadium](https://github.com/GrapheneOS/Vanadium) (by @thestinger, but I doubt he has time for that).

If that happens then maybe one day I might downstream some patches.

I have always offered working and separate patches for Bromite since day 1, it has a cost but it is the only way to allow project open source forks and continuation.
