### ISSUE TITLE
firefox user-agent as default

### ISSUE THREAD

**Issue by disdaogitacc** [kiwibrowser/src#153]
does kiwi support custom user-agent? i mean is it possible to make firefox android user-agent as default? if so could you please guide me through the code.(i'm actually building from source)

**Comment by kiwibrowser** [comment]
Easiest is to change in
https://github.com/kiwibrowser/src/blob/b1ea3ea95d8ac15fc0b49acd83ba2f8b1aaa8d2b/content/common/user_agent.cc#L156
(it's based on 
https://github.com/kiwibrowser/src/blob/master/components/version_info/version_info.cc
)

but you can also check the code how "Desktop mode" functions, because in this mode, it overrides the user-agent (and this is doable directly from the Java code as far as I know)

**Comment by mikhoul** [comment]
You could also use an extension like https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg?hl=fr
