### ISSUE TITLE
Can't update via Play Store

### ISSUE THREAD

**Issue by HunterZ** [kiwibrowser/src#193]
I originally installed Kiwi from the Google Play Store, but the last two releases will not install. It downloads the update a few times in a loop, then gives up. This is not a general Play Store issue, because other apps update fine.

As a workaround, I have been installing the APKs released here in GitHub, which seem to work fine.

I have a sneaking suspicion that Play Store is trying to download the wrong architecture flavor for my Kindle Fire HD10 2019 tablet or something.

**Comment by kiwibrowser** [comment]
The GitHub edition is signed with my personal development key (me, as Kiwi Browser).
The Play Store edition is signed by Google, after their team checked the browser and made sure it is safe to use.

For security reasons, it is not possible to update GitHub version from Play Store, or Play Store version from GitHub
This is why the update process is looping for you, because you have the GitHub edition, the Play Store update refuses to install itself on top.

**Comment by HunterZ** [comment]
Wait! I am only installing releases from github marked Play Store!

I believe I also tried uninstalling the app completely and installing from Play Store, and had the same looping problem.
