### ISSUE TITLE
Github repo makes Kiwi unresponsive

### ISSUE THREAD

**Issue by andre-dierker** [kiwibrowser/src#241]
Hello,

open this repo makes Kiwi unresponsive: https://github.com/SelfhostedPro/selfhosted_templates/blob/master/Template/template.json
Kiwi starts loading and stuck then, only killing the browser and fast close the tab helps.

**Comment by czoins** [comment]
works fine for me

**Comment by rancidfrog** [comment]
Works fine here.

But, on the other hand - https://translate.google.com/
lags a lot when I am typing sentences to translate. Often midsentence kiwi becomes unresponsive for a long while.

Also, I get the long-press text pop-up sometimes for no reason, and am unable to remove it from screen,
![](https://i.imgur.com/kI8oclE.jpg) 
It might pop-up due to previous long-press but new site has opened and no long-press occurs, and it is stuck displaying pop-up

**Comment by Oranko** [comment]
Both issues appear to be fixed in the latest version :)
