### ISSUE TITLE
“No window with id” error when calling chrome.tabs.captureVisibleTab

### ISSUE THREAD

**Issue by mrcoles** [kiwibrowser/src#304]
I received a report from a user of the [GoFullPage Chrome extension](https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en) that they were encountering an error when screenshotting pages with the extension in Kiwi.

This happened on various webpages, including https://example.com/

The error happened during a call to `chrome.tabs.captureVisibleTab(…)` and the error message was:

> No window with id: 1.

This code works fine on Chrome and Edge.

System details:

* Browser version via user agent: Chrome 87.0.4280 (does Kiwi come up as Chrome in the user agent?)
* Samsung tablet (Android 8.1)

**Comment by kiwibrowser** [comment]
Hello Peter,

Thanks a lot for reporting the issue about the captureVisibleTab method.
The API is simply not implemented.

The error you see about the unknown window is actually a side-effect but in reality it's because it's just not implemented.

On Android there is no concept of "windows" because there is only one window, and the concept of tabs is a bit different (tabs on Desktop are always active, whereas on mobile half of them are actually "fake" tabs that are just frozen/snapshots), among other things.

Because of that, all the APIs that interact with a window or a tab had to be reimplemented.

Also, on Android the window system is not "aura", and this causes some additional complexity if to grab the viewport from an API perspective.

There is no timeframe for this API to be implemented, and realistically there is more chance that a full-page screenshot feature gets added in Kiwi (there is even a 90% functional code if you look deep in the repo) but I hope it'll clarify what is going on (so you don't think it's the fault of your extension).

Arnaud.

**Comment by csehszlovakze** [comment]
Bummer. I'm the one who originally reported the issue to mrcoles, and my workaround sadly had to be to save the articles in question for later and then do the page capture in desktop Vivaldi.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
