### ISSUE TITLE
Night mode setting on tablet is not remembered

### ISSUE THREAD

**Issue by gabrielfin** [kiwibrowser/src#315]
If you enable "Night mode" and then close the app and reopen it, the setting is again disabled. This happens only in tablets. In phones, the feature works correctly.

This is the same bug as https://github.com/kiwibrowser/android/issues/32, which as you can see, is almost 2 years old already.

Please fix this issue, as it is very annoying to have to reenable the setting on each launch.

**Comment by SumatraPeter** [comment]
- [Tablet : dark mode unset on each launch](https://github.com/kiwibrowser/android/issues/32) (https://github.com/kiwibrowser/android/issues/32)
- [Feature Request: Default Night Mode](https://github.com/kiwibrowser/android/issues/130) (https://github.com/kiwibrowser/android/issues/130)
- [Night Mode by default feature (for Tablets)](https://github.com/kiwibrowser/src/issues/138) (https://github.com/kiwibrowser/src/issues/138)
- [Night mode setting on tablet is not remembered](https://github.com/kiwibrowser/src/issues/315) (https://github.com/kiwibrowser/src/issues/315 - Current issue)

More than two years have passed and this issue is well-known, so I'm wondering if some Kiwi Browser developer can kindly let us know:

1. Why is this problem restricted to tablets alone?
2. More importantly, why is it not being fixed? Is it just that no-one cares to do it thinking it is just an irritating but trivial annoyance? Or no-one who knows how has the time to spare? Or perhaps there's some technical reason why it can't? In which case, it would be appreciated if this was plainly stated and all these issues closed once and for all.

No offence meant to anyone working on this otherwise fine browser, to whom thanks are of course due. It's just that I (and other tablet owners) clearly find it terribly aggravating to have to turn this setting on Every. Single. Time. the browser is launched. When ALL other settings are remembered fine, what's so special about this one?

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
