### ISSUE TITLE
kiwibrowser forks cannot build the browser for multiple errors in the script

### ISSUE THREAD

**Issue by touhidurrr** [kiwibrowser/src#373]
Action 'automatic build of apk' is not working for multiple errors.

**Comment by touhidurrr** [comment]
It seems ubuntu-latest cannot run some bash scripts. There was some other errors that I couldn’t find out the reason why.

**Comment by radmorecameron** [comment]
From what I can tell, it looks like line this line being different is causing the problem
Chromium:
https://chromium.googlesource.com/chromium/src/+/refs/heads/main/build/install-build-deps.sh#105
kiwi:
https://github.com/kiwibrowser/src/blob/master/build/install-build-deps.sh#L119

But there might be more that I'm missing.  You can also try updating
https://github.com/kiwibrowser/src/edit/master/.github/workflows/build_apk.yml#L22
to be 
`runs-on: ubuntu-18.0.4`
instead of
`runs-on: ubuntu-latest`

**Comment by touhidurrr** [comment]
`runs-on: ubuntu-18.0.4`
Already tried it. Still Errors.
